version: "3.9"

services:
  task_manager:
    image: tm_docker_v1.02:latest
    container_name: tm_docker_v1.02
    volumes:
      - static_volume:/user_tm/static
      - media_volume:/user_tm/media
    env_file:
      - .env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate && gunicorn -b 0.0.0.0:8000 tsk_manager.wsgi:application"

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: task_manager_nginx
    image: task_manager_nginx
    volumes:
      - static_volume:/user_tm/static
      - media_volume:/user_tm/media
    depends_on:
      - task_manager
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:
